Lyssal\GeographyBundle\Entity\AdministrativeArea:
    type: entity

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 128
            nullable: false

    manyToOne:
        country:
            targetEntity: Country
            inversedBy: administrativeAreas
            nullable: false
            onDelete: CASCADE

    oneToMany:
        subAdministrativeAreas:
            targetEntity: SubAdministrativeArea
            mappedBy: administrativeArea
