Lyssal\GeographyBundle\Entity\Country:
    type: entity

    id:
        id:
            type: smallint
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 128
            nullable: false
        codeAlpha2:
            type: string
            length: 2
            nullable: true
        codeAlpha3:
            type: string
            length: 3
            nullable: true

    oneToMany:
        administrativeAreas:
            targetEntity: AdministrativeArea
            mappedBy: country
        languages:
            targetEntity: Language
            mappedBy: country
