Lyssal\GeographyBundle\Entity\PostalCode:
    type: entity

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        code:
            type: string
            length: 5
            nullable: false
        description:
            type: string
            length: 255
            nullable: true

    manyToMany:
        cities:
            targetEntity: City
            inversedBy: postalCodes
            cascade: ['persist']
            joinedColumn:
                nullable: false
                onDelete: CASCADE
